apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydjangowebsite-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: deploy/kustomize/overlays/staging
    repoURL: https://github.com/randommm/mydjangowebsite
    targetRevision: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
