apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydjangowebsite
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: deploy/kustomize/overlays/production
    repoURL: https://github.com/randommm/mydjangowebsite
    targetRevision: production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydjangowebsite-argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: deploy/argo-events
    repoURL: https://github.com/randommm/mydjangowebsite
    targetRevision: HEAD
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
